In [2]:
!pip install pandas

Requirement already satisfied: pandas in e:\python - data analyst\venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in e:\python - data analyst\venv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\python - data analyst\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\python - data analyst\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in e:\python - data analyst\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
!pip install numpy

Requirement already satisfied: numpy in e:\python - data analyst\venv\lib\site-packages (2.4.2)

In [4]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [8]:
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [32]:
print('=' *50)
print('step1 : data loaded')
print('='*50)

==================================================
step1 : data loaded
==================================================

In [9]:
print(f"Rows:{df.shape[0]}, columns:{df.shape[1]}")

Rows:1470, columns:35

In [33]:
print('='*50)
print('step2: explore data')
print('='*50)

==================================================
step2: explore data
==================================================

In [34]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,salary_band,tenure_band,High_Rish,High_Risk,AttritionFlag
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,6,4,0,5,medium,Senior(6-10y),0,0,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,3,10,7,1,7,medium,Senior(6-10y),0,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,3,0,0,0,0,low,New(0-2y),0,0,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,8,7,3,0,low,Senior(6-10y),0,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,3,2,2,2,2,medium,New(0-2y),0,0,0

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   str
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   str
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   str
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  OverTime                  1470 non-null   str
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StockOptionLevel          1470 non-null   int64
 25  TotalWorkingYears         1470 non-null   int64
 26  TrainingTimesLastYear     1470 non-null   int64
 27  WorkLifeBalance           1470 non-null   int64
 28  YearsAtCompany            1470 non-null   int64
 29  YearsInCurrentRole        1470 non-null   int64
 30  YearsSinceLastPromotion   1470 non-null   int64
 31  YearsWithCurrManager      1470 non-null   int64
 32  salary_band               1470 non-null   str
 33  tenure_band               1470 non-null   str
 34  High_Rish                 1470 non-null   int64
 35  High_Risk                 1470 non-null   int64
 36  AttritionFlag             1470 non-null   int64
dtypes: int64(27), str(10)
memory usage: 425.1 KB

In [36]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,High_Rish,High_Risk,AttritionFlag
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,...,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129,0.068707,0.068707,0.161224
std,9.135373,403.509100,8.106864,1.024165,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,...,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136,0.253042,0.253042,0.367863
min,18.000000,102.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,...,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,0.000000,0.000000,0.000000
50%,36.000000,802.000000,7.000000,3.000000,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,...,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,0.000000,0.000000,0.000000
75%,43.000000,1157.000000,14.000000,4.000000,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,...,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000,0.000000,0.000000,0.000000
max,60.000000,1499.000000,29.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,...,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,1.000000,1.000000,1.000000

In [37]:
df.describe(include='all')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,salary_band,tenure_band,High_Rish,High_Risk,AttritionFlag
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470,1470,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,4,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,very high,Senior(6-10y),NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,556,448,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1024.865306,2.721769,...,2.761224,7.008163,4.229252,2.187755,4.123129,NaN,NaN,0.068707,0.068707,0.161224
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,602.024335,1.093082,...,0.706476,6.126525,3.623137,3.222430,3.568136,NaN,NaN,0.253042,0.253042,0.367863
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,491.250000,2.000000,...,2.000000,3.000000,2.000000,0.000000,2.000000,NaN,NaN,0.000000,0.000000,0.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1020.500000,3.000000,...,3.000000,5.000000,3.000000,1.000000,3.000000,NaN,NaN,0.000000,0.000000,0.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1555.750000,4.000000,...,3.000000,9.000000,7.000000,3.000000,7.000000,NaN,NaN,0.000000,0.000000,0.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,2068.000000,4.000000,...,4.000000,40.000000,18.000000,15.000000,17.000000,NaN,NaN,1.000000,1.000000,1.000000

In [17]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [38]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
salary_band                 0
tenure_band                 0
High_Rish                   0
High_Risk                   0
AttritionFlag               0
dtype: int64

In [19]:
print('='*50)
print('step3 : clean data')
print('='*50)

==================================================
step3 : clean data
==================================================

In [25]:
cols_to_drop=['EmployeeCount','Over18','StandardHours']
df.drop(columns=cols_to_drop, inplace=True)
print(f"following columns dropped:{cols_to_drop}")

following columns dropped:['EmployeeCount', 'Over18', 'StandardHours']

In [22]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [26]:
df['AttritionFlag']=df['Attrition'].apply(lambda x: 1 if x=='Yes' else 0)

In [25]:
df.head(15)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AttritionFlag
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,0,8,0,1,6,4,0,5,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,4,1,10,3,3,10,7,1,7,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,2,0,7,3,3,0,0,0,0,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,0,8,3,3,8,7,3,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,4,1,6,3,3,2,2,2,2,0
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,8,4,...,3,0,8,2,2,7,7,3,6,0
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,10,3,...,1,3,12,3,2,1,0,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,11,4,...,2,1,1,2,3,1,0,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,12,4,...,2,0,10,2,3,9,7,1,8,0
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,13,3,...,2,2,17,3,2,7,7,7,7,0
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,14,1,...,3,1,6,5,3,5,4,0,3,0
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,15,4,...,4,0,10,3,3,9,5,0,8,0
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,16,1,...,4,1,5,1,2,5,2,4,3,0
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,18,2,...,3,1,3,2,3,2,2,1,2,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,19,3,...,2,0,6,4,3,4,2,0,3,1

In [27]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
AttritionFlag               0
dtype: int64

In [28]:
df.isnull().sum().sum()

np.int64(0)

In [29]:
print('='*50)
print('step4: add calculated columns')
print('='*50)

==================================================
step4: add calculated columns
==================================================

In [40]:
def salary_band(salary):
    if salary<3000:
        return 'low'
    elif salary<6000:
        return 'medium'
    elif salary<1000:
        return 'high'
    else:
        return 'very high'
    
df['SalaryBand'] =df['MonthlyIncome'].apply(salary_band)

In [41]:
print(df['SalaryBand'])

0          medium
1          medium
2             low
3             low
4          medium
          ...
1465          low
1466    very high
1467    very high
1468       medium
1469       medium
Name: SalaryBand, Length: 1470, dtype: str

In [42]:
print(df[['MonthlyIncome','SalaryBand']])

      MonthlyIncome SalaryBand
0              5993     medium
1              5130     medium
2              2090        low
3              2909        low
4              3468     medium
...             ...        ...
1465           2571        low
1466           9991  very high
1467           6142  very high
1468           5390     medium
1469           4404     medium

[1470 rows x 2 columns]

In [43]:
print(df['SalaryBand'].value_counts())

SalaryBand
very high    556
medium       519
low          395
Name: count, dtype: int64

In [47]:
def tenure_band(years):
    if years<=2:
        return 'New(0-2y)'
    elif years<=5:
        return 'Mid(3-5y)'
    elif years<=10:
        return 'Senior(6-10y)'
    else:
        return 'Veteran(10+y)'
    
df['TenureBand'] = df['YearsAtCompany'].apply(tenure_band)

In [48]:
print(df['TenureBand'])

0       Senior(6-10y)
1       Senior(6-10y)
2           New(0-2y)
3       Senior(6-10y)
4           New(0-2y)
            ...
1465        Mid(3-5y)
1466    Senior(6-10y)
1467    Senior(6-10y)
1468    Senior(6-10y)
1469        Mid(3-5y)
Name: TenureBand, Length: 1470, dtype: str

In [49]:
print(df[['TenureBand', 'YearsAtCompany']])

         TenureBand  YearsAtCompany
0     Senior(6-10y)               6
1     Senior(6-10y)              10
2         New(0-2y)               0
3     Senior(6-10y)               8
4         New(0-2y)               2
...             ...             ...
1465      Mid(3-5y)               5
1466  Senior(6-10y)               7
1467  Senior(6-10y)               6
1468  Senior(6-10y)               9
1469      Mid(3-5y)               4

[1470 rows x 2 columns]

In [50]:
print(df['TenureBand'].value_counts())

TenureBand
Senior(6-10y)    448
Mid(3-5y)        434
New(0-2y)        342
Veteran(10+y)    246
Name: count, dtype: int64

In [19]:
low_satisfaction = df['JobSatisfaction'] <=2
low_income_threshold = np.percentile(df['MonthlyIncome'],25)
low_income = df['MonthlyIncome']<low_income_threshold
young_employee = df['Age']<35

df['High_Risk'] = (low_income & low_satisfaction & young_employee).astype(int)

In [20]:
print(df['High_Risk'])

0       0
1       0
2       0
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: High_Risk, Length: 1470, dtype: int64

In [21]:
print(df['High_Risk'].value_counts())

High_Risk
0    1369
1     101
Name: count, dtype: int64

In [22]:
print('='*50)
print('step5: Key business insights')
print('='*50)

==================================================
step5: Key business insights
==================================================

In [27]:
total_employee = len(df)
attrition_count = df['AttritionFlag'].sum()
attrition_rate = (attrition_count/total_employee)*100
print(attrition_rate)
print(f"total_employee:{total_employee} | Left: {attrition_count}")

16.122448979591837
total_employee:1470 | Left: 237

In [29]:
dept_attrition = df.groupby('Department').agg(
    TotalEmployees = ('AttritionFlag', 'count'),
    AttritionCount = ('AttritionFlag', 'sum')
).reset_index()

dept_attrition['AttritionRate%'] = (
    dept_attrition['AttritionCount']/ dept_attrition['TotalEmployees'] *100
).round(1)

print(dept_attrition.to_string(index=False))

            Department  TotalEmployees  AttritionCount  AttritionRate%
       Human Resources              63              12            19.0
Research & Development             961             133            13.8
                 Sales             446              92            20.6

In [44]:
print(df.columns.to_list())

['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'salary_band', 'tenure_band', 'High_Rish', 'High_Risk', 'AttritionFlag', 'SalaryBand']

In [46]:
salary_attrition = df.groupby('SalaryBand').agg(
    TotalEmployees = ('AttritionFlag','count'),
    AttritionCount = ('AttritionFlag','sum')
).reset_index()

salary_attrition['AttritionRate%'] = (
    salary_attrition['AttritionCount']/ salary_attrition['TotalEmployees'] *100
).round(1)

print(salary_attrition.to_string(index=False))

SalaryBand  TotalEmployees  AttritionCount  AttritionRate%
       low             395             113            28.6
    medium             519              66            12.7
 very high             556              58            10.4

In [51]:
tenure_attrition = df.groupby('TenureBand').agg(
    TotalEmployees = ('AttritionFlag', 'count'),
    AttritionCount = ('AttritionFlag', 'sum')
).reset_index()

tenure_attrition['AttritionRate%'] = (
    tenure_attrition['AttritionCount'] / tenure_attrition['TotalEmployees'] * 100
).round(1)

print(tenure_attrition.to_string(index=False))

   TenureBand  TotalEmployees  AttritionCount  AttritionRate%
    Mid(3-5y)             434              60            13.8
    New(0-2y)             342             102            29.8
Senior(6-10y)             448              55            12.3
Veteran(10+y)             246              20             8.1

In [53]:
print('average monthly income : left vs stayed ')
income_comparison = df.groupby('Attrition')['MonthlyIncome'].mean().round(1)
print(income_comparison)

average monthly income : left vs stayed
Attrition
No     6832.7
Yes    4787.1
Name: MonthlyIncome, dtype: float64

In [55]:
print('monthly income statistics - numpy:')
income_arr = df['MonthlyIncome'].values
print(f"Mean: ${np.mean(income_arr):,.0f}")
print(f"Median :{np.median(income_arr):,.0f}")
print(f"Std Dev: {np.std(income_arr):,.0f}")
print(f"25th percentile: {np.percentile(income_arr,25):,.0f}")
print(f"75th percentile: {np.percentile(income_arr,75):,.0f}")
print(f"90th percentile: {np.percentile(income_arr,90):,.0f}")

monthly income statistics - numpy:
Mean: $6,503
Median :4,919
Std Dev: 4,706
25th percentile: 2,911
75th percentile: 8,379
90th percentile: 13,776

In [57]:
print('high risk employee summary:')
high_risk_summary = df[df['High_Risk']==1].groupby('Department').agg(
    High_Risk_Count = ('High_Risk', 'sum'),
    AttritionAmongHighRisk = ('AttritionFlag', 'sum')
).reset_index()

print(high_risk_summary.to_string(index=False))

high risk employee summary:
            Department  High_Risk_Count  AttritionAmongHighRisk
       Human Resources                7                       3
Research & Development               71                      26
                 Sales               23                      12

In [59]:
print('='*50)
print('Exporting data')
print('='*50)

==================================================
Exporting data
==================================================

In [60]:
df.to_csv('hr_clean_data.csv', index=False)
dept_attrition.to_csv('hr_dept_summary.csv', index=False)
df[df['High_Risk']==1].to_csv('hr_high_risk.csv', index=False)

In [61]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in e:\python - data analyst\venv\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in e:\python - data analyst\venv\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in e:\python - data analyst\venv\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\python - data analyst\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [62]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

In [64]:
df_clean = pd.read_csv('hr_clean_data.csv')
#connect to postgreSQL
username = "postgres"
password = quote_plus("Forgotpass@123")
host = "localhost"
port = "5432"
database = "attrition_analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#load dataframe into postgreSQL
table_name = "hr_attrition"
df_clean.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'hr_attrition' in database 'attrition_analysis'.